-- =============================================================================
-- Metadata registration for SysSequence. Apps that adopt the metadata-starter
-- sequence module must include this snippet in their `2.Metadata.dml.sql`
-- (or run it via SysPreDataService.loadPreSystemData) so that the framework
-- knows the model exists, that it is multi-tenant, and how to expose it as
-- a generic CRUD via ModelController.
--
-- multi_tenant=true ensures EntityService / ModelService auto-filter
-- WHERE tenant_id=? on every read and auto-fill tenant_id on every insert.
-- =============================================================================

DELETE FROM sys_model WHERE model_name = 'SysSequence';
DELETE FROM sys_field WHERE model_name = 'SysSequence';

INSERT INTO sys_model(label_name, model_name, table_name, description, default_order, display_name, search_name, timeline, id_strategy, soft_delete, soft_delete_field, active_control, multi_tenant, version_lock, data_source, service_name, business_key, partition_field)
    VALUES('System Sequence', 'SysSequence', 'sys_sequence', 'Per-tenant sequence configuration and counter', '', 'code', 'code', false, 'DistributedLong', false, '', false, true, true, '', '', 'code', '');

INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('ID', 'id', 'id', 'SysSequence', '', 'Long', '', '', '', '', '', '', '', '', '', 32, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Tenant ID', 'tenantId', 'tenant_id', 'SysSequence', '', 'Long', '', '', '', '', '', '', '', '', '', 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Code', 'code', 'code', 'SysSequence', 'Convention: ModelName.fieldName for auto-fill', 'String', '', '', '', '', '', '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Template', 'template', 'template', 'SysSequence', 'Format template, e.g. EMP-{yyyy}-{seq:5}', 'String', '', '', '', '', '', '', '', '', "''", 128, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Start Value', 'startValue', 'start_value', 'SysSequence', '', 'Long', '', '', '', '', '', '', '', '', '1', 32, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Increment Step', 'incrementStep', 'increment_step', 'SysSequence', 'v1 enforces 1', 'Integer', '', '', '', '', '', '', '', '', '1', 0, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Current Value', 'currentValue', 'current_value', 'SysSequence', 'Last allocated value', 'Long', '', '', '', '', '', '', '', '', '0', 32, 0, false, 1, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Reset Cadence', 'resetCadence', 'reset_cadence', 'SysSequence', 'NONE / YEARLY / MONTHLY / DAILY', 'String', '', '', '', '', '', '', '', '', "'NONE'", 16, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Last Reset Key', 'lastResetKey', 'last_reset_key', 'SysSequence', '', 'String', '', '', '', '', '', '', '', '', '', 16, 0, false, 1, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Mode', 'mode', 'mode', 'SysSequence', 'NO_GAP / ALLOW_GAP', 'String', '', '', '', '', '', '', '', '', "'NO_GAP'", 16, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Status', 'status', 'status', 'SysSequence', 'Active / Disabled', 'String', '', '', '', '', '', '', '', '', "'Active'", 16, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Description', 'description', 'description', 'SysSequence', '', 'String', '', '', '', '', '', '', '', '', '', 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', 'Text');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Version', 'version', 'version', 'SysSequence', '', 'Integer', '', '', '', '', '', '', '', '', '0', 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Created Time', 'createdTime', 'created_time', 'SysSequence', '', 'DateTime', '', '', '', '', '', '', '', '', '', 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Created ID', 'createdId', 'created_id', 'SysSequence', '', 'Long', '', '', '', '', '', '', '', '', '', 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Created By', 'createdBy', 'created_by', 'SysSequence', '', 'String', '', '', '', '', '', '', '', '', '', 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Updated Time', 'updatedTime', 'updated_time', 'SysSequence', '', 'DateTime', '', '', '', '', '', '', '', '', '', 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Updated ID', 'updatedId', 'updated_id', 'SysSequence', '', 'Long', '', '', '', '', '', '', '', '', '', 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, join_model, join_left, join_right, cascaded_field, filters, default_value, length, scale, required, readonly, translatable, non_copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type, widget_type)
    VALUES('Updated By', 'updatedBy', 'updated_by', 'SysSequence', '', 'String', '', '', '', '', '', '', '', '', '', 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '', '');
