package io.softa.starter.user.service.impl;

import java.lang.reflect.Method;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import io.softa.framework.orm.annotation.SkipPermissionCheck;
import io.softa.starter.user.dto.UserAccountDTO;
import io.softa.starter.user.dto.UserProfileDTO;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * User provisioning must not be subject to row scope.
 *
 * <p>Creating an account writes three rows the same call mints: the account, the person, and the
 * person's credentials. Row scope answers "which existing rows may this caller reach", so for ids
 * generated by this very call it has no answer — and it fails closed on {@code UserProfile} and
 * {@code UserIdentity}, which nothing a business role holds references. The concrete symptom: a role
 * granted "create employee" and nothing else creates the Employee row, then dies provisioning that
 * employee's login, with an error naming a model the caller never asked to touch and the whole
 * create rolled back.
 *
 * <p>These assertions are the only thing standing between that and a silent regression: removing the
 * annotation compiles, passes every other test, and only fails in production for non-admin roles —
 * admins short-circuit the check and never see it. What authorizes provisioning is the action that
 * led here (the endpoint gate on {@code /Employee/createOne} and friends), which is checked before
 * any of these methods is reached.
 *
 * <p><b>Scope of the waiver</b>: provisioning only. The business entity that triggered it keeps its
 * own CREATE scope check in {@code ModelServiceImpl.createList}, so a role restricted to one
 * department subtree still cannot place an employee outside it — that is asserted where it lives,
 * not here.
 */
class ProvisioningScopeWaiverTest {

    private static void assertWaived(Class<?> type, String method, Class<?>... params) throws Exception {
        Method m = type.getDeclaredMethod(method, params);
        assertNotNull(m.getAnnotation(SkipPermissionCheck.class),
                type.getSimpleName() + "." + method + " provisions rows it mints itself and must carry "
                        + "@SkipPermissionCheck — without it a role that may create an employee cannot "
                        + "create that employee's login. See the method's javadoc.");
    }

    @Test
    @DisplayName("account provisioning entry points waive row scope")
    void accountProvisioningWaivesRowScope() throws Exception {
        assertWaived(UserAccountServiceImpl.class, "registerInvitedUser",
                String.class, String.class, String.class);
        assertWaived(UserAccountServiceImpl.class, "registerNewUser",
                UserAccountDTO.class, UserProfileDTO.class);
    }

    @Test
    @DisplayName("the person + credentials write waives row scope")
    void profileProvisioningWaivesRowScope() throws Exception {
        // The single choke point: every provisioning path reaches UserProfile and UserIdentity
        // through here, and it is the only place in main code that constructs either.
        assertWaived(UserProfileServiceImpl.class, "registerUserProfile",
                Long.class, UserProfileDTO.class);
        // The /join twin: a first-time invitee's person and credentials row, minted before any
        // session exists. Same rows, same reason, and the only other place that constructs them.
        assertWaived(UserProfileServiceImpl.class, "createPersonForJoin", String.class);
    }
}
