debug: false
system:
  name: Demo Application
  app-code: demo-app
  public-access-url: http://localhost
  metadata:
    public-key:
security:
  encryption:
    password: 12345678
    algorithm: AESEncryption

spring:
  data:
    redis:
      root-key: demo_test
      host: localhost
      port: 6379
      database: 0
      password: admin
      timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://non-prod-mysql.c5c24ag20xb9.ap-southeast-1.rds.amazonaws.com:3306/test_hcm?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: test_hcm_user
    password: StrPwd_2026!
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariPool
#  elasticsearch:
#    cluster: http://localhost:9200
#    username: your_username
#    password: your_password
#    index:
#      changelog: demo_test_changelog
